### ISSUE TITLE
Version 2.0 Roadmap

### ISSUE THREAD

**Issue by MiWeiss** [sciunto-org/python-bibtexparser#318]
While we keep versions 1.x with as few changes as possible, to ensure backward compatibility for the >1000 projects using it, we are currently working on version 2 which will bring major advantages.

This issue aims to keep track of major steps to be conducted until the version 2 branch can take over as main branch of this repository. This is intended to be a dynamic list, continuously changing its content :-)

Details will be discussed in standalone issues assigned with the [v2](https://github.com/sciunto-org/python-bibtexparser/labels/v2) label.

** Nonfunctional Tasks ** 
- [ ] Setup build infrastructure (dependency management, pyproject.toml, ...)
- [ ] Github actions for v2 branch.
- [ ] Documentation (readthedocs) need major improvement.
- [ ] Linting (black, isort, ...)

** Functional Tasks **
- [ ] Define and implement middleware for standard use cases (TBD).
- [ ] Tests, tests, tests

@michaelfruth and @MiWeiss  are primarily working on this. If you want to join v2 dev, feel free to post below which of these points you want to take over. More, already more precisely defined work can be found in the issues list.

**Comment by MiWeiss** [comment]
Version 2.0 is now main branch and this roadmap is nearly completed. This issue is thus closed and for remaining points, new issues will be opened
